### ISSUE TITLE
Second Review

### ISSUE THREAD

**Issue by DualWield** [DualWield/ife-1024#2]
1. GoldContainer 并不需要用到 new createjs.Container()，Container用于整体的移动，而这边只是一个gold的容器，可以用数组代替。
2. handleLoadComplete应该完全处理异步的逻辑，其他初始化，比如

```
     createjs.Ticker.timingMode = createjs.Ticker.RAF;
        createjs.Ticker.addEventListener('tick', tick);
```

应该放在init函数里面。
1. 一些命令需要改正，比如satge,如果想表达实例的意思，改成instance比较好。
2. 变量的初始化使用undefined，而不是null， 参考链接：http://www.ruanyifeng.com/blog/2014/03/undefined-vs-null.html
3. 不变的变量应该大写，比如

```
    var keydownCode = {
        left: 37,
        right: 39
    };
```
1. gameInfo.start = true; 这边start 命令不是很好，可以改为isPause ，start 让人感觉是一个开始函数，而且这个变量并没有用到 =_=

先这样吧 ....

**Comment by Gxsghsn** [comment]
undefined和null竟然有区别..没文化了
